version: "3.8"
services:
  promotion-db:
    image: postgres:15-alpine
    container_name: promotion-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
